import json
import streamlit as st
from datetime import datetime
from utils.state import get_all_causes, CATEGORY_COLORS


def render_report_panel():
    st.markdown("---")
    st.markdown("### 📄 Post-Mortem Report")

    inc    = st.session_state.incident
    causes = get_all_causes()

    with st.expander("View & Export Report", expanded=False):
        # ── incident summary table ───────────────────────────────────────
        sev = inc.get("severity", "—")
        sev_color = {
            "P1 - Critical": "#ef4444",
            "P2 - High":     "#f97316",
            "P3 - Medium":   "#eab308",
            "P4 - Low":      "#22c55e",
        }.get(sev, "#8b949e")

        st.markdown(f"""
| Field | Value |
|---|---|
| **Title** | {inc.get('title') or '—'} |
| **Date** | {inc.get('date') or '—'} |
| **Severity** | <span style="color:{sev_color};font-weight:700">{sev}</span> |
| **Service** | `{inc.get('service') or '—'}` |
| **Owner** | {inc.get('owner') or '—'} |
| **Effect** | {inc.get('effect') or '—'} |
""", unsafe_allow_html=True)

        st.markdown("#### Root Causes")

        populated = {cat: v for cat, v in causes.items() if v}
        if populated:
            for cat, cat_causes in populated.items():
                color = CATEGORY_COLORS.get(cat, "#8b949e")
                st.markdown(
                    f'<div style="color:{color};font-weight:700;margin:0.6rem 0 0.2rem;">'
                    f'▸ {cat}</div>',
                    unsafe_allow_html=True,
                )
                for c in cat_causes:
                    st.markdown(f"- {c}")
        else:
            st.caption("No causes recorded yet.")

        st.markdown("---")

        # ── export buttons ───────────────────────────────────────────────
        col1, col2 = st.columns(2)
        ts = datetime.now().strftime("%Y%m%d_%H%M")

        with col1:
            st.download_button(
                "⬇️ Markdown",
                data=_build_markdown(inc, causes),
                file_name=f"rca_{ts}.md",
                mime="text/markdown",
                use_container_width=True,
            )
        with col2:
            st.download_button(
                "⬇️ JSON",
                data=json.dumps({"incident": inc, "causes": causes}, indent=2),
                file_name=f"rca_{ts}.json",
                mime="application/json",
                use_container_width=True,
            )


def _build_markdown(inc: dict, causes: dict) -> str:
    lines = [
        f"# RCA Report: {inc.get('title') or 'Untitled'}",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Date | {inc.get('date') or '—'} |",
        f"| Severity | {inc.get('severity') or '—'} |",
        f"| Service | {inc.get('service') or '—'} |",
        f"| Owner | {inc.get('owner') or '—'} |",
        "",
        "## Problem Statement",
        f"> {inc.get('effect') or '—'}",
        "",
        "## Root Cause Analysis (Ishikawa / 6M)",
        "",
    ]
    for cat, cat_causes in causes.items():
        if cat_causes:
            lines.append(f"### {cat}")
            for c in cat_causes:
                lines.append(f"- {c}")
            lines.append("")

    lines += [
        "---",
        "*Generated by Fishbone RCA Analyzer*",
    ]
    return "\n".join(lines)
